### ISSUE TITLE
1300 hour weather only

### ISSUE THREAD

**Issue by oeon** [SLUGIS/smokeybear#7]
Let's try only pulling from the 1300 weather reading with the 'O' (observed) values.

**Comment by kaysabelle** [comment]
Which tag is the time? I thought it was `nfdr_tm` but there are also `one_hr`, `ten_hr`, `hu_hr`...

**Comment by oeon** [comment]
can we just run the cron at/around 1300 local time?

**Comment by kaysabelle** [comment]
Yes. Will change the cron on digitalocean shortly.

**Comment by kaysabelle** [comment]
Updated cron to run at 1300 every day.
![screenshot from 2015-05-12 13 04 18](https://cloud.githubusercontent.com/assets/5252186/7597315/7c2d3df6-f8a7-11e4-8da8-0da9e3398313.png)

**Comment by oeon** [comment]
![capture](https://cloud.githubusercontent.com/assets/271851/7751429/c0970ac4-ff8e-11e4-9dc7-b99a751f0c82.PNG)

**Comment by kaysabelle** [comment]
Took another look at this. For some reason it was running twice each day at weird times: once because of sludev and once because of root. Found out that digitalocean runs on UTC so 1300 hours PST is 2000 hours UTC.

I deleted the sludev crontab entry and changed the root crontab entry to 2000 hours. It worked today at 1300 PST, but I'm leaving this issue open for now so we can wait a few days and verify that it works.
